import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'IrmAI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <header>
        <link rel="icon" href="/images/irmai-favicon.png" sizes='any' />
      </header>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
