import { textAlign } from "html2canvas/dist/types/css/property-descriptors/text-align";

const styles = {
  container: {
    position: "relative",
    backgroundColor: "#0b0216",
    color: "#fffbf2",
    fontFamily: "Poppins",
    width: "100%",
    height: "100%",
    display: "flex",
    textAlign: "center",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    flexWrap: "nowrap",
  },
  auraImage: {
    position: "relative",
    minWidth: "100%",
    minHeight: "100%",
    objectFit: "cover",
  },
  safeZone: {
    position: "absolute",
    width: "100%",
    height: "100%",
    padding: "250px 36px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    flexWrap: "nowrap",
  },
  header: {
    position: "absolute",
    top: "200px",
    left: "36px",
    right: "36px",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headline: {
    textAlign: "right",
    fontFamily: "Cirka",
    fontStyle: "normal",
    letterSpacing: "-0.025em",
    fontSize: 50,
    lineHeight: 1,
  },
  headerSep: {
    position: "absolute",
    top: "286px",
    left: "36px",
    width: "100%",
    height: "1px",
    backgroundColor: "#fffbf2",
  },
  content: {
    position: "absolute",
    top: "322px",
    left: "36px",
    right: "36px",
    height: "auto",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
  },
  firstQuestion: {
    fontSize: 60,
    fontFamily: "Cirka",
    fontStyle: "normal",
    letterSpacing: "-0.025em",
    color: "white",
    marginTop: 30,
    padding: "0 10%",
    lineHeight: 1.4,
    whiteSpace: "pre-wrap",
  },
  conclusion: {
    fontSize: 40,
    fontFamily: "Poppins",
    fontStyle: "normal",
    letterSpacing: "-0.025em",
    color: "white",
    marginTop: 30,
    padding: "0 10%",
    lineHeight: 1.4,
    whiteSpace: "pre-wrap",
  },
} as const;

export default styles;
